### ISSUE TITLE
WARNING: Could not create system preferences directory

### ISSUE THREAD

**Issue by jgarciao** [flathub/cat.xtec.clic.JClic#2]
There are a couple of warnings shown in the command line

- Starting the app:
```
$ flatpak run cat.xtec.clic.JClic 
d’abr. 22, 2020 7:59:27 A. M. java.util.prefs.FileSystemPreferences$2 run
WARNING: Could not create system preferences directory. System preferences are unusable.
```
- Closing the app:
```
d’abr. 22, 2020 7:59:36 A. M. java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 32694.
d’abr. 22, 2020 7:59:36 A. M. java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
```

[This question](https://stackoverflow.com/questions/23960451/java-system-preferences-under-different-users-in-linux) at stack overflow seems related to this warning message

**Comment by olea** [comment]
I think this is an expected behavior and AFAIK doesn't broke the user preferences.

@frncesc, what do you think?

**Comment by frncesc** [comment]
It's just a warning. Can be safely ignored.

In the Java platform there are "system preferences" and "user preferences". When no system preferences are set, the first user who starts the program attempts to update them to the default values. If the user cannot do this (which is what happens when they do not have system administration permissions), this warning is displayed.

**Comment by olea** [comment]
Closing: not a bug.

**Comment by jgarciao** [comment]
Thanks!
